tphakala/birdnet-go

internal/config/config.go

`LoadCustomSpeciesConfidence` function has been modified to search for the custom species confidence file in the default config paths. This ensures that the file is found even if it is located in different directories on different operating systems.
Fixes #15

Refactor loading custom species confidence

---

cmd/realtime/realtime.go
internal/analysis/realtime.go
internal/conf/config.go
internal/myaudio/capture.go
internal/myaudio/rstp.go

This PR adds support for multiple RTSP streams, streams are configured by listing --rtsp setting multiple times for each stream

feat: Initial support for multiple RTSP streams

---

views/elements/sidebar.html

Finding myself trying to click the logo to go to the home of the Birdnet-Go quite often... This PR adds a link to the root when pressing the logo

Add link to web root when clicking on logo

---

internal/analysis/processor/processor.go
internal/analysis/realtime.go
internal/imageprovider/imageprovider.go
internal/imageprovider/imageprovider_test.go
internal/imageprovider/wikipedia.go
internal/mqtt/client.go
internal/mqtt/client_test.go
internal/mqtt/mqtt.go
internal/telemetry/debug.go
internal/telemetry/endpoint.go
internal/telemetry/metrics.go
internal/telemetry/metrics/birdnet.go
internal/telemetry/metrics/imageprovider.go
internal/telemetry/metrics/mqtt.go

The telemetry package has been refactored to a modular structure to improve code organization and maintainability. The package now consists of multiple modules, each responsible for a specific aspect of telemetry data collection and processing.
Added metrics collection to MQTT module
Added BirdNET processing time metrics

refactor: telemetry package refactored to modular structure

---

.github/FUNDING.yml

Fix merge conflict

---

doc/recommended_hardware.md

This is my initial list of my reccomendations. Feel free to add upon this! 
Starts work on https://github.com/tphakala/birdnet-go/issues/118 and will eventually close that.

Documentation of Recommended Hardware

---

internal/birdnet/rangefilter.go

Before making this change running `birdnet-go range print` would show only the species with a confidence level of 0.03 or greater, regardless of the threshold defined in config.yaml, or passed in to the `--threshold` parameter.
```
root@birdnetgo-6c6c57f4d4-spbjx:/data# birdnet-go range print --model latest --threshold 0.0001
BirdNET-Go build date: 2024-06-09T12:53:30Z, using config file: /root/.config/birdnet-go/config.yaml
BirdNET GLOBAL 6K V2.4 FP32 model initialized, using 4 threads of available 4 CPUs
2024/08/22 09:52:07 Using latest range filter model
Included species for 52.XXXX, 1.XXXX on date 2024-08-22, week 32, threshold 0.000100
Scientific Name                   Common Name                       Score 
--------------------------------- --------------------------------- ------ …
```

Respect the BirdNET.RangeFilter.Threshold setting when filtering species

---

internal/birdnet/birdnet.go
internal/conf/config.go
internal/conf/validate.go
views/settings/mainSettings.html

This PR adds support for custom classifiers (external model files) and their labels

feat: add support for custom classifiers

---

doc/building.md

Updates build notes to include note about docker engine for buildx and edits a little for clarity.

Devcontainer Docker Notes

---

views/elements/sidebar.html
views/index.html

Use recently added version string for cache busting js and css content

Add cache busting for js and css files

---

install.sh

- Added an option to skip audio input configuration, allowing users to configure it later via the BirdNET-Go web interface.
- Updated the audio input selection prompt to include a third option for later configuration.
- Removed validation of the audio device.
- Improved user guidance with clear messages regarding the new configuration options.
fixes https://github.com/tphakala/birdnet-go/issues/384 and https://github.com/tphakala/birdnet-go/discussions/404

refactor: enhance audio input configuration in install script

---

views/settings/audioSettings.html

- Enhanced audio source selection logic to allow for case-insensitive matching.
- Updated bitrate input handling to ensure valid values and default to '128k' when only 'k' is entered.
- Improved user guidance with tooltips for bitrate input, ensuring clarity on valid formats and conditions.

refactor: improve audio settings configuration and validation

---

Taskfile.yml
assets/custom.css
assets/tailwind.css
assets/util.js
internal/datastore/interfaces.go
internal/datastore/model.go
internal/datastore/mysql.go
internal/datastore/sqlite.go
internal/httpcontroller/handlers/dashboard.go
internal/httpcontroller/handlers/detections.go
internal/httpcontroller/handlers/handlers.go
internal/httpcontroller/handlers/species.go
internal/httpcontroller/handlers/weather.go
internal/httpcontroller/middleware.go
internal/httpcontroller/routes.go
internal/httpcontroller/template_functions.go
views/dashboard.html
views/elements/actionMenu.html
views/elements/confirmModal.html
views/elements/reviewModal.html
views/fragments/detectionDetails.html
views/fragments/listDetections.html
views/fragments/recentDetections.html
views/index.html

This PR adds action menu for detections listing, menu contains actions
- Review detection
- Ignore species
- Delete detection
Review option allows user to mark detection as correct or false positive, a comment also can be added for future reference.
Ignore species action adds species to exclude/ignore list to avoid future detections of that species.
Delete detection removes detection from database including related audio file and spectrogram image.

feat: action menu for detections

---

internal/mqtt/client.go
internal/mqtt/client_test.go
internal/mqtt/mqtt.go

- Enhanced MQTT client with robust connection and publish handling
- Added comprehensive test suite with improved error handling and retry mechanisms
- Implemented context cancellation and timeout handling for MQTT operations
- Added debug logging and retry strategies for network-related scenarios
- Introduced default configuration with configurable timeouts
- Improved DNS resolution and connection error handling
fixes https://github.com/tphakala/birdnet-go/issues/417

refactor: improve MQTT client reliability and testing

---

internal/datastore/model.go

Update database schema to fix detection deletes failing on FOREIGN KEY constraint failures
- Added cascade delete constraints for Note, Results, NoteReview, and NoteComment
- Enhanced foreign key definitions with explicit references and indexing
- Added `not null` constraints to foreign key fields
- Improved referential integrity for related database models

refactor: improve GORM model constraints and foreign key definitions

---

assets/tailwind.css
views/elements/actionMenu.html
views/elements/reviewModal.html
views/fragments/listDetections.html
views/fragments/recentDetections.html

Added status column to detection listing showing
- Review status (correct or false positive)
- Lock status
- Comment status

feat: Add status column

---

internal/httpcontroller/handlers/settings.go
internal/myaudio/capture.go

- Add check to prevent unnecessary RTSP reconfiguration when no RTSP settings are changed
- Implement hasRTSPSettings function to detect RTSP-related form parameters
- Optimize ReconfigureRTSPStreams to handle empty RTSP URL scenarios more efficiently
- Move FFmpeg monitor stop logic to the beginning of the function for clearer control flow

refactor: Improve RTSP stream configuration and settings handling

---

internal/birdnet/data/labels/labels_pt.txt

Portugese label file was missing species entries, this fixes https://github.com/tphakala/birdnet-go/issues/451

fix: replace portugese label file with valid one

---

views/elements/actionMenu.html
views/fragments/listDetections.html

This PR improves action menu positioning logic, menu opens down or up based on available space on screen. Z positioning is also fixed with small parent containers so that menu is not cut off.

fix: Position action menu based on screen space

---

internal/datastore/interfaces.go
internal/httpcontroller/handlers/detections.go
internal/imageprovider/imageprovider_test.go
views/elements/actionMenu.html
views/elements/reviewModal.html
views/fragments/listDetections.html

and fix HTMX refresh for detection actions such as review status change or delete

fix: Add working pagination for hourly results ..

---

install.sh

- Add comprehensive update and cleanup functionality for BirdNET-Go installation
- Improve error handling and user interaction during installation process
- Implement version checking, container management, and systemd service updates
- Add clean installation and uninstallation options
- Enhance location detection with fallback mechanisms
- Improve logging and error reporting

feat: Enhance install script with robust update and cleanup mechanisms

---

assets/tailwind.css
internal/analysis/control_monitor.go
internal/analysis/processor/mqtt.go
internal/analysis/processor/processor.go
internal/analysis/realtime.go
internal/httpcontroller/handlers/mqtt.go
internal/httpcontroller/handlers/settings.go
internal/httpcontroller/routes.go
internal/httpcontroller/server.go
internal/mqtt/client.go
internal/mqtt/client_test.go
internal/mqtt/mqtt.go
internal/mqtt/testing.go
views/settings/integrationSettings.html

- Implement comprehensive MQTT connection testing with multi-stage validation
- Add new MQTT testing endpoint in HTTP controller
- Create control monitor for dynamic MQTT service reconfiguration at runtime
- Enhance frontend with interactive MQTT connection test UI
- Improve error handling and troubleshooting hints for MQTT connectivity issues
fixes https://github.com/tphakala/birdnet-go/issues/489

feat: Add MQTT connection testing and configuration management

---

internal/conf/utils.go
internal/httpcontroller/handlers/audio_level_sse.go
internal/observation/observation.go

Sanitize RTSP URL before applying it to Note to avoid sensitive information leaking with actions
fixes https://github.com/tphakala/birdnet-go/issues/519

refactor: Centralize RTSP URL sanitization in conf package

---

views/pages/about.html

I like the 'evil' inverted color logo in the about page but I do not think it was intentional 😄

logo invert fix

---

internal/httpcontroller/middleware.go

- Removed the client IP parsing and local subnet security check from the CSRFMiddleware function.
- Updated the middleware to directly return the CSRF middleware configuration.
- Adjusted comments for clarity regarding cookie security settings.

refactor: simplify CSRFMiddleware by allowing cookies over HTTP

---

assets/custom.css
assets/tailwind.css
internal/httpcontroller/template_functions.go
views/fragments/birdsTable.html

- Updated CSS for responsive table adjustments across various screen sizes, including new media queries for extra large, large, medium-large, and medium screens.
- Introduced compact styles for hour cells and thumbnail columns to improve layout on smaller devices.
- Added a new utility function `roundToNearest` in template_functions.go to round numbers to the nearest multiple, enhancing data presentation in the UI.
- Updated HTML to reflect changes in CSS classes for total detections visibility based on screen size.
- Improved progress bar styling with new width classes for better visual representation of detection data.

fix: enhance responsive design and add utility functions

---

internal/analysis/realtime.go
internal/diskmanager/disk_usage_unix.go
internal/diskmanager/file_utils_test.go
internal/diskmanager/mocks/mock_functions.go
internal/diskmanager/policy_age.go
internal/diskmanager/policy_age_test.go
internal/diskmanager/policy_usage.go
internal/diskmanager/policy_usage_test.go

- Updated AgeBasedCleanup and UsageBasedCleanup functions to return the number of clips removed and current disk utilization percentage.
- Improved logging to provide feedback on cleanup success, including the number of clips removed and disk utilization after cleanup operations.
- Added unit tests to verify the return values of cleanup functions, ensuring accurate reporting of metrics.
- Introduced mock functions for testing disk usage and audio file retrieval, enhancing test coverage and reliability.

refactor: enhance cleanup functions to return detailed metrics

---

internal/analysis/file.go
internal/myaudio/readfile.go
internal/myaudio/readfile_flac.go
internal/myaudio/readfile_wav.go

- Introduced an EOF signal mechanism in audio processing to improve chunk handling and ensure all data is processed before completion.
- Updated the `AudioChunkCallback` to accept an additional parameter indicating EOF status.
- Implemented logic in `processAudioFile` to manage EOF signals and ensure proper termination of processing loops.
- Enhanced `readFLACBuffered` and `readWAVBuffered` functions to signal EOF correctly, improving robustness for large audio files.
- Added a new method `readWAVDirectBytes` for efficient processing of extremely large WAV files, ensuring memory management and performance.
- Debug logging has been improved to provide better insights during audio processing.

feat(myaudio): enhance audio file processing with EOF handling

---

assets/js/components/multiStageOperation.js
assets/tailwind.css
internal/birdweather/testing.go
internal/httpcontroller/handlers/birdweather.go
views/components/multiStageOperation.html

This PR enhances the BirdWeather integration testing UI with several usability and visual improvements.
Changes
DNS Configuration Warning
- Moved the DNS Configuration Issue warning from individual test results to a dedicated, prominent section
- Improved warning display with consistent styling while ensuring text readability on both light and dark themes
- Enhanced detection of different types of DNS resolution issues
Interactive Rate Limit Timer
- Implemented a live countdown timer for rate limit messages
- Added backend support to provide expiry timestamps to the frontend
- Created a visually clear timer that updates in real-time showing minutes:seconds remaining
- Added automatic "Retry Test" button that appears when the rate limit period expires
- Improved rate limit message wording …

Birdweather test fixes

---

support.sh

- Introduced a new script to collect diagnostic information for troubleshooting BirdNET-Go issues.
- The script gathers system, Docker, BirdNET-Go configuration, systemd service, audio device, and installation information while masking sensitive data.
- Outputs a support bundle in a tarball format for easy sharing with developers.
This addition enhances the troubleshooting process and improves user support capabilities.

feat(support.sh): add BirdNET-Go support data collection script

---

assets/audio-processors/pcm-audio-processor.js
assets/audio-processors/test-processor.js
assets/tailwind.css
internal/httpcontroller/handlers/websocket.go
internal/httpcontroller/htmx_routes.go
internal/httpcontroller/server.go
internal/myaudio/capture.go
internal/myaudio/capture_buffer.go
internal/myaudio/ffmpeg_input.go
views/elements/audioLevelIndicator.html

- Added AudioStreamManager to handle WebSocket connections for audio streaming.
- Introduced new route for audio streaming in htmx_routes.go.
- Updated Server struct to include AudioStreamManager.
- Implemented methods for broadcasting audio data and managing client connections.
- Enhanced audio capture logic to broadcast data to WebSocket clients.
- Improved audio processing in the frontend to handle streaming and playback controls.
These changes enable real-time audio streaming capabilities, enhancing user experience and interactivity.

feat(audio): implement WebSocket audio streaming and management

---

frontend/src/lib/desktop/features/dashboard/components/RecentDetectionsCard.svelte
frontend/static/messages/en.json

- Adjusted column layout in RecentDetectionsCard to include species and confidence headers, improving data presentation.
- Replaced common name and thumbnail columns with a combined species column that includes confidence indicators.
- Updated styles with RD prefix to avoid conflicts and enhance responsiveness.
- Added new translation keys for species and confidence in en.json to support the updated layout.
These changes enhance the user experience by providing clearer information in the detections UI.

refactor: update RecentDetectionsCard layout and translations
