tphakala/birdnet-go

.dockerignore
Dockerfile

Hi, I am really happy to see this project coming along nicely! One issue I always had with the original BirdNET-Pi project was that is did not support docker. Which made it really hard to try out before deciding to run it on a raspberry, since it pretty much required a dedicated VM...
While the go approach for this project makes it way easier to try out, I still believe a docker image could be beneficial! Therefore, I would like to make a contribution on getting us started with a initial dockerfile.
This PR allows for BirdNET-Go to be built and bundled into a container. The container will by default execute
the realtime command, starting the server. The image is currently based on debian bookworm since I found that easiest to get running. However, in the future it might be better bundle …

Add initial Dockerfile setup

---

.dockerignore
.github/workflows/docker-build.yml
Dockerfile

Implements a basic github action job that will for every commit to the main branch, build and push a docker
image to the latest tag. The latest tag will get overwritten after each commit.
In the future it might be better to instead decide on some better tagging strategy.

Add basic github action for building docker image

---

.dockerignore
.github/workflows/docker-build.yml
Dockerfile
README.md

Defines a /config and /data volume for the docker image where the end-user can mount in filesystems from the host. Allowing for these volumes to persist outside the container.
I also added a very basic example on how to run the container in the README.md. It can probably be improved a bit, but it is a start!

Define docker volumes & add docker documentation

---

.github/workflows/docker-build.yml
Dockerfile
README.md

I'm using podman and had some issues with the most recent change. This adds the runtime user to the audio group, and adds instructions on how to mount in the audio devices to the container.

Enable usage of rootless docker

---

README.md

It always ended up picking the wrong mic for me inside the container. Found out that the ALSA_CARD environment variable can be used for specifying which mic to use. Added some documentation about it.

Add info on how to select capture device in container

---

Dockerfile
cmd/realtime/realtime.go
internal/conf/config.go
internal/myaudio/capture.go

adding very basic support for RTSP.
usage: `birdnet-go realtime --rtsp rtsp://...`
if an rtsp URL is not provided, it will default to using the audio device.
I've been running this for the past week without issues.
resolves #12

support RTSP by using `ffmpeg` to convert the stream

---

internal/analysis/processor/dogbarkfilter.go
internal/analysis/processor/processor.go
internal/conf/config.go
internal/conf/consts.go

BirdNET model is often incorrectly detecting dog barks as owls, this commit implements a filter which tracks dog barks and filters out user configured species detections if it happens within 5 minutes of last dog bark detection.
Species which are filtered by dog bark filter are configured in dog_bark_filter.cvs in BirdNET-Go config directory, file content should be species name per line, species can be common name or scientific name like:
ural owl
strix uralensis
Filter must be enabled in config file by setting
realtime:
dogbarkfilter:
enabled: true

feat(processor) add dog bark filter which can be used to track recent dog barks to filter out regularly occuring false detections

---

cmd/realtime/realtime.go
internal/conf/config.go
internal/myaudio/capture.go

By default ffmpeg will use UDP when streaming from an RTSP source. Some setups (in my case when running the docker container in a Kubernetes cluster) won't work with a UDP connection, and so require a TCP connection instead.
This PR adds in an --rtsptransport flag, which defaults to udp, but can be set to tcp if required.
This is my first attempt working with Go, so please feel free to point me in the right direction if there's a better way to be doing something!

Add in a --rtsptransport flag to realtime command

---

internal/conf/config.go

The container did not start as expected anymore since this [commit](https://github.com/tphakala/birdnet-go/commit/94b19e7de8e5075f91f614a022a455def05a53fc) introduced some weird indents.
Got the following two errors:
> Created default config file at: /root/.config/birdnet-go/config.yaml
Error loading configuration: error initializing viper: While parsing config: yaml: line 36: found character that cannot start any token
> Created default config file at: /root/.config/birdnet-go/config.yaml
Error loading configuration: error initializing viper: While parsing config: yaml: line 46: found character that cannot start any token
My pull request fixes it by indenting correctly. Maybe we could add some sort of workflow to start the container and do some smaller tests in order to catch issues like …

Fix invalid indents in default config

---

internal/httpcontroller/handlers.go
internal/httpcontroller/routes.go
internal/httpcontroller/utils.go
views/fragments/recentDetections.html
views/fragments/speciesDetections.html

spectrogram images are now generated after page has been loaded, images are loaded lazily improving responsiveness of UI, sox is also ran with lower priority on Linux and like operating systems.

enh(ui): improve spectrogram generation to enable lazy loading of images

---

.github/workflows/docker-build.yml

As mentioned before, I thought it would be nice to have some sort of verification of the docker images. This pr adds such a feature by starting the image and giving it 5 sec to respond to a http request. Only if it responds within time, then the docker image(s) will be pushed to the registry.
Had to do a bit of fighting with the github action runner since it does not contain any alsa devices, causing the container to not start properly. I was able to work around this by installing the alsa dummy soundcard. Unfortunately, there appears to be certain issues with ubuntu-22 due to recent kernel changes, meaning that I had to downgrade to ubuntu-20.04 for this to work. However, there is a discussion ongoing on getting the ubuntu-22 runner behaving as expected in the …

Test docker image before pushing to registry

---

.devcontainer/devcontainer.json
Dockerfile
Makefile

Recently there has been many new users who would like to get started with the project. To make it easier to start contributing to the project it might be beneficial to have a devcontainer setup.
This pr adds a very basic devcontainer that on startup will start a "dev_server" which was also added to the makefile. This dev_server is in reality just making use of the [air](https://github.com/cosmtrek/air) tool for hot reloading on any code changes. I would assume that might be how development is supposed to be done since there is already a .air.toml file :)
Will try to make another pull request soon where I update the docs a bit to mention the devcontainer.

Add initial devcontainer integration

---

.devcontainer/devcontainer.json
.devcontainer/postCreateCommand.sh

I'm trying to use the devcontainer myself for development now. Found some missing dependencies that I thought could be useful to have in it.
- **Add golangci-lint to devcontainer**
- **Add golang extension to devcontainer**
- **Add github cli to devcontainer**

Improve devcontainer setup

---

.github/workflows/golangci-test.yml

Adds a basic unit test workflow job that will run on every pull request. It makes use of [gotestfmt](https://github.com/GoTestTools/gotestfmt) to format the console output in a nice way.

Add unit test job

---

AUTHORS
README.md
internal/birdweather/birdweather.go
internal/conf/config.go

Added location fuzzing support for BirdWeather uploads, you can add location precision in meters to config.yaml, however this seems to require some support from BirdWeather backend also, request sent to Tim to support this.
Config example
birdweather:
enabled: false		  # true to enable birdweather uploads
locationaccuracy: 500   # accuracy of location in meters
debug: false		  # true to enable birdweather api debug mode
id: 00000			  # birdweather ID

feat(birdweather) Birdweather location fuzzing

---

views/index.html

`new Date().toISOString()` always returns the current time in UTC, so when it's after UTC midnight, but still before UTC midnight of the previous day (say, at 10 PM in New York), the date picker defaults to tomorrow, which will never contain any data.
This changes to use `toLocaleString` to ensure the date picker always reflects the browser's local today date. It uses the Swedish (`sv`) locale simply because they use an `YYYY-MM-DD` date format, which is the most useful in this case

Default date picker to local time zone

---

cmd/realtime/realtime.go
internal/analysis/processor/actions.go
internal/analysis/processor/processor.go
internal/analysis/realtime.go
internal/conf/config.go
internal/conf/config.yaml
internal/conf/defaults.go
internal/httpcontroller/updateconfig.go
internal/myaudio/capture.go

Add Realtime.Audio.Source setting which allows user configurable audio source, it defaults to "sysdefault" on Linux. Audio clip retention policy settings are moved under Realtime.Audio.Export node.

feat(audio): make audio source user configurable

---

internal/analysis/realtime.go

When the clip cleanup process tries to delete a clip file, and the OS reports that the file does not exist, this will now detect that condition and still attempt to clear the clipPath from the clip.
Closes #149

Clear clip path from note during cleanup when clip is missing

---

.github/workflows/docker-build.yml
.github/workflows/release-build.yml

As mentioned before, docker images were not getting the release tags since workflows were missing for it. This PR adds a docker release tagging job to the release-build workflow. The job downloads the image with corresponding git hash and tags it with the release number. It makes use of the docker/metadata-action to strip the **v** from the release version since that appears to be the common approach. Meaning that v1.2.3 would become just 1.2.3. In addition it always tags with the latest tag.
In addition, the normal docker building workflow which is triggered for every commit, is modified to no longer tag with :latest, but rather with :dev. Meaning that those who want something relatively stable can use the :latest tag while those who want to live risky can use :dev
--- Demo ---
Creating …

Add release tagging of docker images

---

.github/workflows/docker-build.yml

Speeds up the docker building process by utilizing one build agent per platform. In addition, better makes use of the github action caching by scoping it per platform. Since one platform would overwrite the other otherwise, resulting in low cache hit rates when building arm64. In addition, moved the testing of the docker image itself into its own job, which the building jobs are now dependent on.
Build times went from ~10 min down to ~2 min when running on github actions.

Improve docker building workflow

---

.github/workflows/docker-build.yml
Dockerfile

Fixes missing x86 build mentioned in #175 
Followed this [guide](https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/) to make improvements to the cross compilation process:
- Make use of `BUILDPLATFORM `in dockerfile to get better docker caching and build speeds, since the platform of the computer used to build the image is used as much as possible, limiting the need for emulation.
- Moves some args around to make fork off the building context as late as possible, resulting in better docker builder layer reuse for different platforms
With the utilization of BUILDPLATFORM, the docker caching works way better for different platforms. Eliminating the need for separate build jobs added in #165. Meaning that only one job will be used again, that builds …

Fix & improve docker multi platform builds

---

internal/conf/config.go
internal/conf/utils.go
internal/conf/validate.go

Settings are now accessible through the conf.Setting() function. This allows direct access to settings without the need to import a Settings pointer into a class or function.
Accessing Settings
```
// Accessing a setting
if conf.Setting().Debug {
fmt.Println("Debug is enabled")
} else {
fmt.Println("Debug is disabled")
}
// Accessing a nested setting
if conf.Setting().Realtime.Audio.Export.Enabled {
fmt.Println("Audio export is enabled")
} else {
fmt.Println("Audio export is disabled")
}
```
Updating Settings at Runtime
```
// Copy current settings
newSettings := *conf.Setting()
// Modify the necessary setting
newSettings.Realtime.Audio.Export.Enabled = true
// Update settings
if err := conf.UpdateSettings(&newSettings); err != nil {
log.Fatalf("Error updating settings: %v", err)
}
```

refactor: Refactor configuration package to improve settings handling

---

internal/conf/config.go
internal/conf/config.yaml
internal/conf/defaults.go
internal/myaudio/audiobuffer.go

Add Realtime.Audio.Export.Debug flag to control audio buffer & export debug messages

refactor: Add audio export debug flag

---

views/fragments/recentDetections.html
views/fragments/searchResults.html
views/fragments/speciesDetections.html

Had the chance to try birdnet-go on an iPad when visiting a relative. Found out that audio playback was not working as expected. It only worked if I first clicked play, then paused, and clicked play again. Based on some [research online](https://meta.discourse.org/t/secure-media-audio-does-not-play-on-safari-on-the-first-click/156124/18) it appears to be fixable by preloading the metadata.
Was able to verify that the changes fixes the playback issues on iPads.

Fix audio playback on safari/ipad

---

internal/analysis/realtime.go
internal/conf/config.go
internal/conf/config.yaml
internal/conf/defaults.go
internal/conf/utils.go
internal/diskmanager/age.go
internal/diskmanager/priority.go
internal/diskmanager/util.go

The priority disk cleanup feature purges recordings based on several policy rules. This helps maintain disk usage within user-defined limits while retaining valuable recordings.
This retention policy will be enabled by default.
1. **Configurable Threshold**:
- Cleanup starts when disk usage exceeds a user-defined threshold (e.g., 80%).
2. **Sorting Policies**:
- **Oldest Files First**: The primary criterion is to delete the oldest recordings first.
- **Species Occurrences**: Files are prioritized for deletion based on the number of occurrences of each species, with species having the most recordings prioritized to be deleted first as these are often least interesting to user
- **Confidence Level**: Files with lower confidence levels are prioritized for deletion over those with higher …

feat: New "priority" cleanup policy

---

Dockerfile

As mentioned in [v0.5.4 release discussion](https://github.com/tphakala/birdnet-go/discussions/185#discussioncomment-9641107)
There have been issues running the linux/arm64 image since PR #176 which fixed the linux/amd64 build and introduced improvements to the cross-compilation process by utilizing BUILDPLATFORM. Since this PR cross-compilation provided by the build system will be used rather than emulation in the docker build. Unfortunately, this change does require some more changes to the Dockerfile/makefile to work as expected.
Currently, the arm64 image contains the amd64 binaries. Due to how the Dockerfile calls the make file without an argument, leading to this piece of code to be executed:
```make
all: $(LABELS_ZIP) $(NATIVE_TARGET)
```
which depends on this:
```make
UNAME_M := …
```

Fix arm64 cross compilation in docker build on amd64

---

internal/analysis/realtime.go
internal/conf/config.yaml
internal/conf/validate.go
internal/myaudio/buffers.go

Previously overlap for realtime process was fixed to 1.5 seconds, now it is set by birdnet.overlap setting which now defaults to 1.5 if it is not set. Setting value is validated to be in range of 0 to 2.9 (seconds).
Overlap has impact on detection accuracy, higher overlap causes more samples to be taken of each 3 second chunks analysed by BirdNET AI model. Overlap setting higher than 1.5 is not recommended for realtime use due to increase in CPU usage.

feat: BirdNET overlap setting impacts now realtime process also

---

.devcontainer/devcontainer.json
.devcontainer/postCreateCommand.sh
.devcontainer/start_dev_server.sh
Dockerfile
Makefile

* Add port forwarding of 8080 in devcontainer such that it will automatically start working, rather than waiting for vscode to detect that it is open
* Air now goes by a new repo name and the reference has been updated
* Now when starting the devcontainer you will be prompted for which recording device to use:
* A dev-user is added for the buildenv stage, meaning that most steps will not run as root directly anymore. For devcontainer users, this has the advantage of being less likely to be able to create root-owned files on the host system

Improve devcontainer experience

---

internal/datastore/interfaces.go
internal/httpcontroller/handlers.go
internal/httpcontroller/routes.go
views/fragments/birdsTableHTML.html
views/fragments/hourlyDetections.html

by clicking hour column you now see all results of that specific hour

feat: add hourly results for daily summary table

---

internal/analysis/processor/actions.go
internal/analysis/processor/processor.go
internal/mqtt/mqtt.go

This commit adds a context with a timeout for publishing MQTT messages in the `MqttAction` and `Client` structs. This ensures that the publish operation does not block indefinitely and provides better error handling. If the publish operation exceeds the timeout, an error is returned indicating a timeout.

fix: Add context timeout for MQTT publish

---

internal/datastore/interfaces.go

When using a MySQL database the hourly occurrences table does not render correctly due to DATE_FORMAT being called on a time field. This MR switches the DATE_FORMAT call for TIME_FORMAT

fix: Hourly occurences not being calculated correctly when using MySQL

---

assets/custom.css
assets/tailwind.css
assets/util.js
internal/conf/utils.go
internal/datastore/interfaces.go
internal/httpcontroller/auth_routes.go
internal/httpcontroller/handlers/detections.go
internal/httpcontroller/routes.go
internal/httpcontroller/template_functions.go
views/dashboard.html
views/fragments/birdsTable.html
views/fragments/listDetections.html
views/index.html

This PR introduces some UI/UX improvements and bug fixes:
- Fixed hour cell links
- Added sticky header for Recent detections table to make the hours more readable
- Enhanced hourly data visualization with gradient-based heatmap backgrounds
- Improved dynamic loading of date picker on dashboard
- Refactored path validation into reusable `IsSafePath` function
- Added duration parameter to detection queries for flexible time ranges
- Updated template functions to handle string/int type conversion
- Enhanced date picker initialization and visibility handling

Fix hour cell links & add sticky headers for Recent detections

---

internal/analysis/file.go
internal/myaudio/readfile.go
internal/myaudio/readfile_flac.go
internal/myaudio/readfile_wav.go
internal/suncalc/suncalc_test.go

This PR implements a concurrent processing system for audio chunk analysis to improve performance and CPU utilization. The new implementation uses a worker pool pattern with goroutines to process multiple audio chunks simultaneously.
- Implemented a worker pool for parallel BirdNET analysis
- Added buffered channels for efficient chunk processing
- Introduced configurable number of worker threads (1-8)
- Added debug logging for troubleshooting
- Improved CPU utilization during analysis
- Uses buffered channels for audio chunk distribution
- Worker count is determined by `BirdNET.Threads` setting:
- If set to 0, uses system CPU count
- Clamped between 1 and 8 workers
- Each worker runs in its own goroutine
- Implements three main goroutine types:
1. Worker routines for BirdNET analysis
2. …

File analysis worker pool

---

internal/myaudio/ffmpeg_input.go

- Added audioWatchdog struct to track the last time data was received from the RTSP source.
- Introduced a goroutine that checks for data reception every 5 seconds and triggers a restart if no data is received for 60 seconds.
- Updated processAudio method to integrate the watchdog, ensuring it updates the last data time upon receiving audio data.
- Enhanced error handling to wait for the watchdog to finish before returning errors related to data reception.

feat: implement audio watchdog for RTSP source monitoring

---

internal/conf/config.go
internal/conf/defaults.go
internal/myaudio/process.go

Added debug flag for BirdNET processing, when enabled all results of segment analysis is printed to log. More debug will be enabled later.

BirdNET debug

---

internal/conf/config.go
internal/conf/defaults.go
internal/conf/validate.go
internal/httpcontroller/handlers/sse.go
views/settings/settingsBase.html

This PR fixes #367 by properly managing one SSE session per client

Fix SSE session handling

---

cmd/realtime/realtime.go
internal/analysis/realtime.go
internal/birdnet/birdnet.go
internal/httpcontroller/handlers/handlers.go
internal/httpcontroller/handlers/settings.go
internal/httpcontroller/server.go

BirdNET model setting changes no longer require application restart

Improve configuration reload

---

assets/custom.css
assets/util.js

This PR fixes various layout issues for Firefox users

Fix layout issues with Firefox

---

internal/analysis/processor/actions.go
internal/analysis/processor/eventtracker.go
internal/analysis/processor/processor.go

- Event tracker functionality was using hard coded interval values, fixed code to use realtime.interval value instead
- MQTT publish action frequency was not controlled by event tracker

Event tracker fixes

---

internal/analysis/processor/actions.go
internal/analysis/processor/processor.go
internal/httpcontroller/handlers/media.go
internal/httpcontroller/middleware.go
internal/httpcontroller/routes.go
internal/httpcontroller/server.go
views/fragments/detectionDetails.html
views/fragments/listDetections.html
views/fragments/recentDetections.html

- Modified audio clip path handling to support both relative and absolute paths
- Improved media serving with proper MIME types and download headers
- Added debug logging with configuration toggle
- Fixed issues with file downloads and incorrect filenames
- Added `sanitizeClipName` function to handle both relative and absolute paths
- Implemented path sanitization to prevent directory traversal
- Added automatic conversion of absolute paths to relative paths
- Removed redundant "clips/" prefix from paths to prevent double directory issues
- Added proper MIME type detection for various audio formats (WAV, FLAC, MP3, M4A, AAC, OPUS)
- Implemented correct Content-Disposition headers for file downloads
- Added Content-Transfer-Encoding and Content-Description headers
- Fixed issue where audio …

fix: Audio clip downloads for non default export paths

---

internal/httpcontroller/handlers/media.go

- Improved the `sanitizeClipName` function to handle path traversal attempts more robustly, including case-insensitive checks for Windows compatibility.
- Added normalization of path separators and ensured the removal of the 'clips/' prefix is case-insensitive.
- Enhanced the `getFullPath` and `getSpectrogramPath` functions for consistent path handling and validation.
- Implemented checks for final path length to prevent exceeding system limits.
- Added detailed debug logging for better traceability during path sanitization and file existence checks.

refactor: enhance clip name sanitization and path handling in media handler

---

internal/analysis/file.go

- Created `processChunk` function to encapsulate chunk processing logic
- Simplified worker goroutine code by moving chunk processing details to a dedicated function
- Maintained existing error handling and species filtering behavior
- Improved code modularity and readability in audio file processing

refactor: reduce complexity of processAudioFile() function

---

internal/analysis/processor/actions.go
internal/analysis/processor/execute.go
internal/analysis/processor/processor.go
internal/analysis/processor/workers.go

The pull request introduces comprehensive thread-safety enhancements to the processor module in the analysis system. The changes focus on adding mutex synchronization to various action types, modifying method receivers to support concurrent access, and refactoring the detection processing logic. The modifications include adding sync.Mutex to multiple action structs, updating method signatures to use pointer receivers, and introducing new methods for handling detection processing and action execution.

refactor: improve memory efficiency and reduce code complexity

---

cmd/benchmark/benchmark.go
internal/analysis/processor/actions.go
internal/analysis/queue/queue.go
internal/analysis/realtime.go
internal/birdweather/birdweather.go
internal/conf/locale.go
internal/conf/utils.go
internal/cpuspec/cpuspec.go
internal/datastore/interfaces.go
internal/datastore/mysql.go
internal/datastore/sqlite.go
internal/diagnostics/capture_debug.go
internal/diagnostics/support_collect.go
internal/diskmanager/policy_usage.go
internal/httpcontroller/auth_routes.go
internal/httpcontroller/handlers/dashboard.go
internal/httpcontroller/handlers/detections.go
internal/httpcontroller/handlers/media.go
internal/httpcontroller/handlers/settings.go
internal/httpcontroller/handlers/statistics.go
internal/httpcontroller/handlers/utils.go
internal/httpcontroller/template_functions.go
internal/logger/filehandler.go
internal/mqtt/client.go
internal/myaudio/capture.go
internal/security/oauth.go
internal/weather/icon_codes.go
main.go

This pull request encompasses a comprehensive set of modifications across multiple files in the codebase, focusing primarily on refining function signatures, improving code clarity, and making syntax updates. The changes span various packages and include updates to method signatures, parameter handling, error management, and octal literal representations. While the modifications do not introduce significant new functionality, they enhance code readability, maintainability, and adhere to modern Go coding conventions.

refactor: fix various linter warnings

---

internal/datastore/interfaces.go
internal/datastore/manage.go
internal/datastore/model.go
internal/datastore/sqlite.go
internal/httpcontroller/handlers/detections.go
views/elements/reviewModal.html

Instead of adding verify and comment columns to notes table this PR adds new tables for review status and comments, this approach avoids slow auto migration process with SQLite with other benefits also

refactor: update database schema to include review and comment tables

---

internal/httpcontroller/auth_routes.go
internal/httpcontroller/handlers/detections.go
internal/httpcontroller/handlers/handlers.go
internal/httpcontroller/middleware.go
internal/httpcontroller/routes.go
internal/httpcontroller/server.go
internal/security/basic.go
views/elements/actionMenu.html
views/fragments/listDetections.html
views/fragments/recentDetections.html

Avoid unauthenticated users from reviewing and deleting detections by protecting routes and UI elements

feat: Hide detection action menu for unauthenticated users

---

internal/datastore/interfaces.go
internal/datastore/manage.go
internal/datastore/model.go
internal/httpcontroller/handlers/detections.go
internal/httpcontroller/routes.go
views/elements/actionMenu.html
views/elements/reviewModal.html

This PR adds functionality to lock important detections to prevent them from being deleted during regular cleanup operations.

feat: Add ability to lock detections to protect them from cleanup

---

internal/analysis/realtime.go
internal/datastore/interfaces.go
internal/datastore/manage.go
internal/datastore/model.go
internal/imageprovider/imageprovider.go
internal/imageprovider/imageprovider_test.go
internal/imageprovider/wikipedia.go

This PR implements a persistent caching mechanism for thumbnail image metadata in the database, improving application performance and reducing external API calls.
- Implements database-backed caching for image metadata (URL, license, author info)
- Cache entries are automatically refreshed after 14 days
- Graceful fallback to live fetching if cache fails
- Memory-efficient storage with size estimation
- Thread-safe implementation with proper error handling
- Reduces application startup time by avoiding redundant API calls
- Minimizes external API usage and network traffic
- Improves reliability by maintaining service during API outages
- Ensures metadata freshness through automatic refresh mechanism
- Uses GORM for database operations
- Implements automatic background refresh routine
- …

feat: Store image provider cache in database to speed up application restarts

---

internal/analysis/realtime.go
internal/myaudio/capture.go

Allow starting application without any working capture device

refactor: improve audio device initialization process

---

internal/analysis/realtime.go
internal/datastore/interfaces.go
internal/diskmanager/file_utils.go
internal/diskmanager/policy_age.go
internal/diskmanager/policy_usage.go
internal/imageprovider/imageprovider_test.go

Audio clips of locked detections are not removed during disk cleanup process

refactor: make diskmanager package respect locked clips during cleanup

---

assets/audioplayer.js
views/fragments/listDetections.html

This PR adds high pass filter for audio player controls, high pass filter allows to remove unwanted rumble from audio clips at playback time

feat: Add high pass filter to audio player

---

.github/workflows/nightly-build.yml
.github/workflows/release-build.yml
Dockerfile
Taskfile.yml
main.go

- Update Dockerfile to use BUILD_VERSION instead of VERSION
- Modify main.go to display version without 'v' prefix
- Update Taskfile.yml to support custom version via BUILD_VERSION
- Enhance GitHub workflows for nightly and release builds to use consistent version detection
- Improve version tagging and manifest creation in CI/CD pipelines

feat: Improve version handling and build process

---

internal/birdnet/data/labels/labels_pt-br.txt

This PR adds a new label file for Portuguese (Brazil), `labels_pt-br.txt`, located in `internal/birdnet/data/labels/`. This allows BirdNET-Go users to utilize species names in Brazilian Portuguese instead of European Portuguese.
- The file was generated using the **eBird API**, ensuring accurate and standardized naming.
- The format follows the same structure as the existing `labels_pt.txt`: Scientific_Name_Portuguese_Brazilian_Name_eBird_Code
- Example lines from `labels_pt-br.txt`:
- Turdus rufiventris_Sabiá-laranjeira_turruf
- Amazona aestiva_Papagaio-verdadeiro_amaaes
- Ara ararauna_Arara-canindé_ararau
- Many Brazilian users prefer **pt-BR labels** instead of pt-PT.
- This enables better species identification for Brazilian birdwatchers.
- Ensures consistency with the **eBird …

Added Portuguese (Brazil) labels file (labels_pt-br.txt)

---

assets/js/components/multiStageOperation.js
internal/analysis/control_monitor.go
internal/analysis/processor/actions.go
internal/analysis/processor/processor.go
internal/api/v2/integrations.go
internal/birdweather/birdweather.go
internal/birdweather/interfaces.go
internal/birdweather/testing.go
internal/httpcontroller/handlers/README.md
internal/httpcontroller/handlers/birdweather.go
internal/httpcontroller/handlers/settings.go
internal/httpcontroller/htmx_routes.go
internal/httpcontroller/middleware.go
views/pages/settings/integrationSettings.html

This PR implements dynamic start and stop functionality for the BirdWeather client during reconfiguration, eliminating the need to restart BirdNET-Go after making configuration changes.

feat: Birdweather dynamic restart on reconfigure

---

views/elements/dashboard.html

- Implemented a new feature to save and retrieve the detection limit from localStorage.
- Added an onchange event to the detection limit select element to trigger saving the selected value.
- Initialized the detection limit from localStorage on page load, ensuring the UI reflects the user's last selection.
- Triggered an htmx request if the saved limit differs from the default value.
fixes feature request https://github.com/tphakala/birdnet-go/issues/543

feat: persist recent detections limit by storing it in browser local storage

---

internal/myaudio/capture.go
internal/myaudio/ffmpeg_input.go
internal/myaudio/ffmpeg_monitor.go
internal/myaudio/ffmpeg_monitor_fuzz_test.go
internal/myaudio/ffmpeg_monitor_test.go
internal/myaudio/ffmpeg_monitor_timing_test.go

- Changed the FFmpeg monitor initialization to use NewDefaultFFmpegMonitor for consistency.
- Moved the ffmpegProcesses variable to ffmpeg_monitor.go to avoid duplicate declarations.
- Introduced comprehensive tests for the FFmpeg monitor, including process management and cleanup functionalities.
- Enhanced the checkProcesses and cleanupOrphanedProcesses methods for better error handling and process management.
fixes https://github.com/tphakala/birdnet-go/issues/558

refactor(myaudio): update FFmpeg monitor initialization and add tests

---

assets/util.js

- Prevents pushing a date (e.g. `192.168.1.100:8080/#2025-03-27`) to the URL when loading the dashboard without any value set (e.g. the root path `192.168.1.100:8080/`).
- Still allows today's date to be set once you start changing it with the picker. 
- Useful when wanting to reload the webpage and always get today's information.
- Resolves https://github.com/tphakala/birdnet-go/issues/571
- Might resolve: https://github.com/tphakala/birdnet-go/issues/585

feat: Prevent redirect from root dashboard path

---

internal/api/v2/analytics.go
internal/api/v2/analytics_test.go
internal/datastore/analytics.go
internal/datastore/interfaces.go

I'm using the `/api/v2/analytics/species/summary` and `/api/v2/analytics/species/daily` endpoints in Home Assistant. 
I really like templating direct URLs to the ebird website so I can view them from my Home Assistant dashboard. But this requires the species code.
e.g.: https://ebird.org/species/amecro
I'd like to add the `species_code` to the bundled analytics summary endpoints. 
I've run this locally and deployed an image to my server. It returns the data as expected. But haven't been able to confirm whether or not the tests work.
Returned data from the server looks good.

Feat: Add Species Code to analytics endpoints

---

assets/util.js
views/elements/dashboard.html

Discovered an issue where the `topBirdsChart` didn't load when the dashboard was loaded on the root path.
This wasn't discovered in my initial testing as I had no birds being recorded on the dev server. 
This issue is now corrected with a new trigger (one which doesn't load the other routes). 
**NOTE**: Since there's no cache clearing mechanism, in order for the redirect to be fixed and the `topBirdsChart` to populate, the cache needs to be cleared on the local device before it will start working as intended. In desktop chrome, you can clear the cache from the network tab. In mobile chrome, this can be done by connecting the device over dev tools (while connected to a desktop in developer mode) and clearing it in the network tab as well (but I don't expect many people to do this).
Shown …

fix: Fix root dashboard to trigger topBirdsChart to render

---

internal/diskmanager/file_utils.go
internal/diskmanager/policy_age_test.go
internal/diskmanager/policy_usage_test.go

AAC Export Type creates `.m4a` files. This PR allows these files to be pruned per the retention policy.

Allow files with .m4a extensions to be cleaned up

---

views/fragments/detectionDetails.html
views/fragments/listDetections.html
views/fragments/recentDetections.html

PR is to make a cosmetic update to the HTML fragments when the audio file/spectrogram fails to load. This utilizes the existing asset `/assets/images/spectrogram-placeholder.svg` to replace the alt text currently being displayed.

Load spectrogram-placeholder.svg on missing Audio Files

---

internal/diskmanager/policy_age.go
internal/diskmanager/policy_usage.go

- Added a sleep interval of 100 milliseconds in both processFiles and performCleanup functions to throttle the cleanup process, improving performance and reducing potential resource contention during file deletion.
- This change enhances the efficiency of file management operations within the disk manager.

feat: throttle cleanup process in disk manager

---

internal/birdweather/birdweather_client.go

- Changed the expected HTTP response status from 200 OK to 201 Created for soundscape uploads.
- This adjustment aligns the response handling with the correct status code for successful resource creation.

fix: update HTTP response status for soundscape upload
